### ISSUE TITLE
Prepopulate Incident Fields via URL params?

### ISSUE THREAD

**Issue by adamhrv** [PartnershipOnAI/aiid#110]
Would it be possible to pre-populate your incident fields via URL params? 
Example:
`https://incidentdatabase.ai/apps/submit?title=My%20New%20Report&Author=FirstName%20LastName`

I'd like to recommend your incident report database for users of the [Exposing.ai](https://exposing.ai) project (written about [here](https://www.nytimes.com/2021/01/31/technology/facial-recognition-photo-tool.html)) who can check if their Flickr photos were used in facial recognition research projects that are contributing to commercial surveillance technologies. Reducing manual data entry could encourage more submissions to your database.

**Comment by smcgregor** [comment]
Hi @adamhrv! Certainly possible, but I would like to understand a bit better how you see the feature being used. While I applaud what exposing.ai is doing, I am not sure how it would fit into the [draft](https://github.com/PartnershipOnAI/aiid/issues/84) or [current](https://incidentdatabase.ai/research) incident definition.

Stepping outside the context of Exposing.ai, I believe there is an easy case to be made for giving report links for specific incidents to communities of interest.

**Comment by smcgregor** [comment]
@cesarvarela let's add support for this so we can add links to the citation pages for adding reports to current incidents.

**Comment by smcgregor** [comment]
This was addressed in #483 and will be deployed to production shortly. Closing in favor of #489 for the remaining advancements.
