### ISSUE TITLE
No Results Display is awkward

### ISSUE THREAD

**Issue by smcgregor** [PartnershipOnAI/aiid#111]
Note: I will shortly be merging the update to the discover app that brings it into the Gatsby application from a separate static JS application. Initially both apps will be in place with one of them hidden from the nav structure, but as soon as all the functionality and UX from the old Discover app is migrated we will fully retire the old app. This is the first of a series of issues I am going to open for completing the switch over.

The no-results behavior has the right sidebar shooting over to the left hand side (see below). The expected behavior is that the facet bars will remain pulled to the right. Additionally, there should be a "no results" message displayed, such as "Your search returned no results. Please clear your search in the search box above or the filters".

<img width="790" alt="Screen Shot 2021-03-20 at 11 53 53 AM" src="https://user-images.githubusercontent.com/64780/111882476-1581bb00-8973-11eb-8662-87dde32d9001.png">

**Comment by alexmcode** [comment]
@smcgregor if pr #126 is ok and merged I think this can be closed
