### ISSUE TITLE
Better Discover App Search Context Awareness

### ISSUE THREAD

**Issue by smcgregor** [PartnershipOnAI/aiid#114]
The separation of the facets and the search string is necessary in screen space but it is a bit awkward. The user does not necessarily know where they are in the search and will forget, for instance, that they have filtered the incident number. I think a redundant encoding may be needed here. Perhaps placing each of the selected facets next to the search bar with a (x) to remove them? I am open to suggestions on this.

**Comment by alexmcode** [comment]
I like the idea of having the selected facets more visible. Maybe place them between the search box and the results?

**Comment by smcgregor** [comment]
Sounds good to me!

**Comment by alexmcode** [comment]
@smcgregor  one more question: should we have all filters (`theguardian.com`, `bbc.com`,`Reuters`, `Roman Yampolskiy` etc) or only filter categories (`source`, `authors`, `submitters` etc)?

**Comment by smcgregor** [comment]
Likely all filters, for example, "(x) Source:theguardian.com (x) Submitter:Roman Yampolskiy"
