### ISSUE TITLE
Facet Search for Dates

### ISSUE THREAD

**Issue by smcgregor** [PartnershipOnAI/aiid#115]
Two things on this,

1) The color of the facets that are selected are a bit close to the color of the header for the facet. Maybe make it lighter?
2) I added a field to the database for Unix epoch dates. This enables date range selection on an additional set of facets. Let's add facets for epoch_incident_date and epoch_date_published. Additional facets for epoch_date_downloaded, epoch_date_submitted, and epoch_date_modified would be useful for me and a few others, but I don't think they are broadly useful for the community. I think they should be displayed as facets if the user is authenticated.

**Comment by alexmcode** [comment]
I think that what would work best would be just 2 date inputs (maybe datetime inputs?) for selecting the range. would you agree?

**Comment by smcgregor** [comment]
The resolution of dates in the database are for the day even if the unix epoch is more specific. You can have a date picker, but not a datetime. I'll update the Algolia index today with these fields and fully merge my pending merge request.

**Comment by smcgregor** [comment]
Algolia index is updated with the epochs and I added them to the supported facets list of the index. Should be ready to integrate with the UI.
