### ISSUE TITLE
Update Navigation to Point to New Discover App

### ISSUE THREAD

**Issue by smcgregor** [PartnershipOnAI/aiid#116]
The current discover app will need to be removed from the navigation of the site and this new discover app will become the target. This requires updating the "about" page for the discover app. This should be in a separate PR and we will hit merge as soon as a few more rough edges are ironed out.

**Comment by alexmcode** [comment]
@smcgregor should this issue be left the last one in the discover app issue batch?

**Comment by smcgregor** [comment]
Yes, you can open the pull request whenever you like, but it will be the last to merge.
