### ISSUE TITLE
Remove Incident Stats from Discover Application

### ISSUE THREAD

**Issue by smcgregor** [PartnershipOnAI/aiid#117]
The incident stats are updating based on the selected facets, but that card is supposed to show the statistics for all the reports submitted for a single incident and not what incident reports are currently displayed. In general the original Discover app was a bit awkward in the way it handles looking at an incident versus filtering and looking through the database. It may be better to scrap the incident detail view in the Discover app entirely and instead have the "Show Details on Incident _" button load the citation page for the incident. If so, the incident citation page will need to have more substantial changes, like: (1) adding a breadcrumb for getting back to the Discover App's previous set of search refinements, (2) add all the report cards to the citation record, (3) change the links to be anchors to the report cards on the page rather than the source publication.

**Comment by alexmcode** [comment]
A few question just to clarify for myself @smcgregor :
>It may be better to scrap the incident detail view in the Discover app entirely

Meaning that we will also remove the second way of viewing the cards (enlarged view)?

>(1) adding a breadcrumb for getting back to the Discover App's previous

Can you please provide some details about this? it will be a simple back button something  like: `Back to Discover App`?

>(2) add all the report cards to the citation record,

right now in the citation page we have a list of links. should we replace this with the cards we see in the discover app (for instance what you see now when you click on "Show Details on Incident _"  button)

>(3) change the links to be anchors to the report cards on the page rather than the source publication.

I assume you are referring to the links from `/cite/[incidentId]`. those should point to the cards that we will be adding in point number (2)?

**Comment by smcgregor** [comment]
> Meaning that we will also remove the second way of viewing the cards (enlarged view)?

yes, but I think the sequence would be (1) add the content elsewhere in the app (primarily on the citation page I think), then (2) remove the enlarged view from the discover app.

> Can you please provide some details about this? it will be a simple back button something like: Back to Discover App?
Also the browser back button works as it should - previous state is preserved (from what I can see). Is there any point in adding an extra back button? (just trying to think critically)

👍 for not including the breadcrumb as a requirement. It will be clear during the initial review if it should be re-added as a requirement.

> right now in the citation page we have a list of links. should we replace this with the cards we see in the discover app (for instance what you see now when you click on "Show Details on Incident _" button)

As you scroll from top to bottom of the citation you should effectively be zooming in from the high level details to the more specific.

HIGH LEVEL
Citation
Statistics Card
list of report titles (anchors to the report cards in the page)
Taxonomy Tags (a feature to be implemented in the future)
Image Carousel
Timeline (a feature to be implemented in the future)
report cards
LOW LEVEL

> I assume you are referring to the links from /cite/[incidentId]. those should point to the cards that we will be adding in point number (2)?

Yep!

**Comment by alexmcode** [comment]
@smcgregor this can be closed?

**Comment by smcgregor** [comment]
I think the buttons in the new discover application need to point to the citation record rather than the detail view you implemented in the discover app.

**Comment by alexmcode** [comment]
Do you mean the corresponding incident card on the citation page?

**Comment by smcgregor** [comment]
I think it should likely link to the top of the `/cite/#` page.
