### ISSUE TITLE
Collect Data

### ISSUE THREAD

**Issue by AllenBlaze** [PartnershipOnAI/aiid#146]
Hi,

I'm Alain, a doctoral student at Laval University, how like to know if there is a way to download all the incidents report in csv for my text mining project.

Thank you

**Comment by smcgregor** [comment]
Hi @AllenBlaze: You can download them on a weekly basis from here. Please reopen the issue if you experience a problem with it. https://incidentdatabase.ai/research#downloadtheindex

**Comment by smcgregor** [comment]
Also, please open an issue with your results!

**Comment by AllenBlaze** [comment]
Thanks a alot !
Yeah I'll share my results. thanks
