### ISSUE TITLE
Rename `IncidentForm` component to `IncidentReportForm`

### ISSUE THREAD

**Issue by alexmcode** [PartnershipOnAI/aiid#174]
Original issue: https://github.com/PartnershipOnAI/aiid/pull/100#discussion_r624877674

@smcgregor please confirm

**Comment by smcgregor** [comment]
Confirmed. Subtle but important difference.

**Comment by smcgregor** [comment]
This is part of the next migration we will do after I clear the one you have in #461

**Comment by cesarvarela** [comment]
Already done
