### ISSUE TITLE
Error for button `Reject New Incident`

### ISSUE THREAD

**Issue by alexmcode** [PartnershipOnAI/aiid#178]
Original issue:  https://github.com/PartnershipOnAI/aiid/pull/100#issuecomment-831054361

New issue: The "Reject New Incident" button on the review queue comes up with a 502 error. Logs indicate "uncaught promise rejection: delete not permitted". I can delete manually after merge so we can see if this is really just a permissions issue, but I think it is likely to persist.

**Comment by smcgregor** [comment]
Delete worked in production. Closing this.
