### ISSUE TITLE
Limit latest incident report image height

### ISSUE THREAD

**Issue by cesarvarela** [PartnershipOnAI/aiid#206]
Otherwise: 

![image](https://user-images.githubusercontent.com/1172479/127415781-530d8382-6ff8-4e45-8a66-6bc13f402386.png)

**Comment by smcgregor** [comment]
@cesarvarela I assigned you expecting a CSS fix. If that is not reasonable, please let me know.

**Comment by cesarvarela** [comment]
I think we could do better overall but that PR fixes it
