### ISSUE TITLE
Use either emotion or styled-components

### ISSUE THREAD

**Issue by cesarvarela** [PartnershipOnAI/aiid#212]
Both packages do mostly the same, so I would suggest using only one.

**Comment by smcgregor** [comment]
Any preference @alexmcode and @cesarvarela?

**Comment by cesarvarela** [comment]
I like `styled-components` more because it is only one package, but some components use some `emotion` features that will make it easier to remove `styled-components.`

**Comment by smcgregor** [comment]
I just spoke with @alexmcode and he is +1 for styled-components.
