### ISSUE TITLE
Classification Workflow Support

### ISSUE THREAD

**Issue by smcgregor** [PartnershipOnAI/aiid#265]
I spoke with the CSET folks and previewed the current editing functionality so we could come to a better understanding of their requirements. We want them to switch over from spreadsheets to working directly within the AIID. The core functionality we have is good, but there are a few features that will make it much easier to work within while the classifications are still in preliminary status. These features are largely those provided by working in the Google Sheets context, which provides a lot of flexibility for sorting, version control etc.

* Comment and freeform review functionality. They need the ability to keep track of notes, uncertainties, TODOs, etc. while an incident is still in the incident annotation process. This can be supported most easily at the moment with a simple text area that is not displayed to users in the UI unless they are auth'd,

* New process view. CSET needs the ability to filter incidents based on their annotation process status. This highlights the need for a generic view into the database that is more similar to a spreadsheet interface. I would like to explore potential database front ends that have been built for generic purposes and could be added along side the Discover app as a view into all the data.

Finally, CSET would like to have some form of version control or history for the process. This is a "nice to have" feature rather than a "need to have" feature, so we will put it beyond the scope of work at the moment.

**Comment by smcgregor** [comment]
@alexmcode Let's proceed with the following,

* Render the CSET taxonomy with react-table and support filtering and the common react-table functionality
* Render the incident data with react-table. Initially just do the incident number, title of one of the reports, and the incident date. We will refine this through review

I will also look at humongous and tableplus to see if their more packaged solutions serve the need better.

Notes on potential table interfaces:

* https://github.com/tannerlinsley/react-table
* https://www.humongous.io/ (Sean to evaluate)
* https://tableplus.com/ (Sean to evaluate)
* https://datatables.net/

**Comment by alexmcode** [comment]
@smcgregor  thanks. one thing I forgot to mention for:
>This can be supported most easily at the moment with a simple text area that is not displayed to users in the UI unless they are auth'd,

we will need to add a new field in the classifications collection alongside `incident_id`, `namespace` and `classifications` fields. In this new field, `notes` we will store the notes that the person editing the classification does. thoughts?

**Comment by smcgregor** [comment]
@alexmcode that sounds good to me. If you update the schema, I will drop it in the backend.
