### ISSUE TITLE
Backups page is blank

### ISSUE THREAD

**Issue by cesarvarela** [PartnershipOnAI/aiid#269]
I think this is a regression? 🤔 

https://incidentdatabase.ai/backups

**Comment by smcgregor** [comment]
How did you find this path? The snapshots are located here: https://incidentdatabase.ai/research/snapshots

That page is created here: https://github.com/PartnershipOnAI/aiid/blob/master/site/gatsby-site/page-creators/createBackupsPage.js#L33

The path you shared should be 404ing, but something is creating a page for it?
