### ISSUE TITLE
 Taxonomy field and classificaiton field missmatch

### ISSUE THREAD

**Issue by alexmcode** [PartnershipOnAI/aiid#276]
The field `Financial Cost` is spelled `Finacial_Cost` in the classification collection and we can't do a match between the 2 in the code

classification collection:
![image](https://user-images.githubusercontent.com/7571224/133439010-2ce3a12c-53a0-4104-91c3-f73710d522d7.png)

taxa collection:
![image](https://user-images.githubusercontent.com/7571224/133439041-55b0f96d-d225-4f65-9d0b-acd95eb62262.png)

**Comment by smcgregor** [comment]
Fixed with: `db.getCollection('classifications').updateMany( { }, {$rename: { 'classifications.Finacial Cost': 'classifications.Financial Cost'} } )`
