### ISSUE TITLE
Algolia Index Is Duplicating

### ISSUE THREAD

**Issue by smcgregor** [PartnershipOnAI/aiid#327]
I am going to check again after the next production build, but I just had to clear the index and upload a fresh copy because the number of records had grown over 2k. Maybe it is not clearing the index when it uploads a new copy on builds?

**Comment by cesarvarela** [comment]
Mmm, it should be merging them based on objectId, checking it now

**Comment by smcgregor** [comment]
It might be a legacy issue. It was merging into the old index that was already there.

**Comment by cesarvarela** [comment]
Yep, I think that's the issue, my Algolia staging index has been sitting around 1,2k items since the first time I created it, and there have been many pushes to it in between.

**Comment by smcgregor** [comment]
Closing this now, I'll reopen if it recurs.
