### ISSUE TITLE
Resolve Dependabot issues

### ISSUE THREAD

**Issue by smcgregor** [PartnershipOnAI/aiid#348]
See: https://github.com/PartnershipOnAI/aiid/security/dependabot

**Comment by cesarvarela** [comment]
I think that's only visible to the repo owner, I see a 404 with my user.

**Comment by smcgregor** [comment]
![Screen Shot 2021-11-22 at 12 25 09 PM](https://user-images.githubusercontent.com/64780/142930203-b1a98147-c88f-4bb9-9c3c-0a8ea2c57316.png)

**Comment by cesarvarela** [comment]
This may lead me to #306 since these seem to be peer dependencies mostly

**Comment by smcgregor** [comment]
Our attack surface in the Gatsby space is not very large at the moment, but we will want to resolve this within the next ~2 months.

**Comment by cesarvarela** [comment]
This should change for the better once the Gatsby 4 update is released.

**Comment by cesarvarela** [comment]
I think what could be done about this without going overboard has been done already.
