### ISSUE TITLE
Add Cypress Test

### ISSUE THREAD

**Issue by cesarvarela** [PartnershipOnAI/aiid#353]
My suggestion would be to use https://www.cypress.io/

**Comment by alexmcode** [comment]
I also support cypress. It's flexible and very powerful. A bit difficult to setup I think but it's a very good option

**Comment by smcgregor** [comment]
Sounds good, I assigned @cesarvarela for the hello world test case.

**Comment by cesarvarela** [comment]
Closing this since the initial release is done, next is #385
