### ISSUE TITLE
Notes field on classifications does not update

### ISSUE THREAD

**Issue by smcgregor** [PartnershipOnAI/aiid#360]

**Comment by alexmcode** [comment]
@smcgregor In order to test this i need to add admin roles to my user - on local MongoDB setup.

@cesarvarela when creating a new user for authenticating with the new auth system do we need to do extra steps to grant edit/admin right to that user?

**Comment by smcgregor** [comment]
@alexmcode There is a realm function that will automatically add the admin role to your user when you create the user in the Realm UI. You need to make sure your development Realm installation has the complete Realm site published as found in the `site/realm` directory.

https://github.com/PartnershipOnAI/aiid/blob/master/site/realm/functions/onNewUser.js
