### ISSUE TITLE
Publish field not exposed on CSET taxonomy

### ISSUE THREAD

**Issue by smcgregor** [PartnershipOnAI/aiid#392]
I am setting the `Publish` bool field on the classification records to get it into the world. This should be exposed to the appropriate taxonomy editor.

**Comment by smcgregor** [comment]
Query used to set it manually in the backend for the CSET taxonomy: `{ 'classifications.Publish': {  $not: {$type: "bool"} }, 'classifications.Annotation Status': "6. Complete and final" }`

**Comment by cesarvarela** [comment]
I think the `Publish` field also needs to be added to the `field_list` of each document in the `taxa` collection for it to appear in the form.

**Comment by smcgregor** [comment]
Sounds good.

**Comment by cesarvarela** [comment]
This is the minimal needed for it work properly:
![image](https://user-images.githubusercontent.com/1172479/152062263-f5ab3570-9aeb-4204-8f8d-3d426881106e.png)

**Comment by smcgregor** [comment]
ok, should I add this now to staging?

**Comment by cesarvarela** [comment]
Sounds good.

**Comment by smcgregor** [comment]
Change made.
