### ISSUE TITLE
Taxonomy for Incident Resources

### ISSUE THREAD

**Issue by smcgregor** [PartnershipOnAI/aiid#405]
This will be a multi-part issue with steps and integrations performed by researchers to develop content for the taxonomy.

### User Story

"As a company shipping an AI product, I want to know how I can prevent this incident from happening with our new product so we will not be {embarrassed, sued, bankrupted}"

### Engineering Activity

* Front end improvements to the taxonomy feature
* Develop pages detailing responsible AI resources

### Mock

![image3](https://user-images.githubusercontent.com/64780/150473958-89f55e06-4aa2-42f8-94d2-bf669ec8dd0d.png)

### Steps

1. Define a new taxa record in the database

```
{
   "namespace":"resources",
   "weight":{
      "$numberInt":"50"
   },
   "description":"# What are these resources?\n\nThe following resources have been associated with incidents in the database to provide tools and processes to persons and companies looking for best practices in the prevention or mitigation of similar incidents in the future.",
   "field_list":[
      {
         "short_name":"Datasheets for Datasets",
         "long_name":"Datasheets for Datasets",
         "short_description":"Document the datasets use would mitigate or prevent the incident",
         "long_description":"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
         "display_type":"bool",
         "mongo_type":"bool",
         "default":null,
         "placeholder":null,
         "permitted_values":null,
         "weight":{
            "$numberInt":"70"
         },
         "instant_facet":true,
         "required":false
      }
   ]
}
```
This should populate a new taxonomy that would be made available here: https://incidentdatabase.ai/research/4-taxonomies

2. Insert the `long_description` field to incidents where the bool value is true in the `classifications` collection. Render it as markdown.

3. Get this in a mergeable state and the next steps will come from someone on the research side of the AIID.

**Comment by cesarvarela** [comment]
@smcgregor the `long_description` field will be the same for every incident?

**Comment by smcgregor** [comment]
Yes. Anything that needs to be more specialized will not be a bool type.

**Comment by cesarvarela** [comment]
I wonder if this is a regression, but should classifications only be visible to authenticated users?

![image](https://user-images.githubusercontent.com/1172479/151426585-1129557e-afe1-4838-b2be-c7bae946ea8f.png)

**Comment by smcgregor** [comment]
@cesarvarela I just logged out and I am not seeing the taxonomy on any of the citation pages. The logic that should be applied is:

1. Is the user an admin/editor? Then show all classifications.
2. Otherwise, show the classifications/taxonomy only if the classification is marked with the `publish` flag.

**Comment by smcgregor** [comment]
We addressed 1 and 2 above.
