### ISSUE TITLE
MongoDB Update

### ISSUE THREAD

**Issue by smcgregor** [PartnershipOnAI/aiid#448]
Hi Sean, 

Your M0/M2/M5 Atlas cluster(s) will automatically be upgraded to MongoDB 5.0 next week. Please note, this automatic upgrade will only impact your shared tier clusters (M0/M2/M5) and will not impact dedicated clusters (M10 or higher). 

If you have not already done so, please ensure you have taken the recommended actions below to ensure a seamless transition. 

What’s in the update?
MongoDB 5.0 introduces new features and improvements such as:
A Stable API, designed to preserve application behavior through upgrades
Native time series collections and clustered indexing
Window functions and new temporal operators
What do I need to do?
To ensure a seamless transition, we recommend you:
Update your driver version to ensure continued compatibility with your applications. Visit our Docs to see which driver versions are compatible with 5.0 and download the latest version.
Remove unsupported commands. In MongoDB 5.0, support for commands like ensureIndex have been removed. Visit our Docs to see a complete list and alternative solutions.
Not ready? 
You can upgrade to a dedicated Atlas cluster for more flexibility and control over when major version updates and maintenance are performed, as well as gain access to premium features like real-time performance metrics, automated data archival, index and schema recommendations, and more.

**Comment by smcgregor** [comment]
@cesarvarela FYI, I will likely hit the buttons to update staging this weekend.

**Comment by smcgregor** [comment]
It looks like I can't update staging manually, so everything will update at once and we will need to debug the build if something pops up.

**Comment by cesarvarela** [comment]
Did dis cause any trouble?

**Comment by smcgregor** [comment]
I don't think it has updated yet, I'll let you know when it automatically does.

**Comment by smcgregor** [comment]
No apparent issues here.
