### ISSUE TITLE
Submit form is Broken

### ISSUE THREAD

**Issue by smcgregor** [PartnershipOnAI/aiid#490]
It looks like there is a problem in the submit form in staging. I found it after merging to production, but I cancelled the build so the issue is not live.

It looks like there is now an inconsistency in the values being pushed to the backend with the update. Specifically,
```
Version currently deployed to staging and sitting on master:
      "authors": "Test Author", # this is not an array

Current working version,
      "incident_id": 0, # this is missing on staging
      "tags": [], # this is missing on staging
      "authors": [ # this is an array
        "Beth Mole"
      ],
```

I think the form submission (preferred) or the server side function needs updating.

**Comment by cesarvarela** [comment]
Looking into it
