### ISSUE TITLE
Improve Review Queue - Deduplication

### ISSUE THREAD

**Issue by smcgregor** [PartnershipOnAI/aiid#50]
Ingesting new incident reports is burdensome because it is necessary to manually check all new reports for an existing incident identifier. New tools for this process would be useful. Some ideas,

## Publication Date Checks

Incident reports that are published or associated with incident dates near the dates of other incident reports are more likely to be associated with existing incidents in the database

## Text Search

The current review queue does not automatically list incidents that have similar terms. Most document similarity indexing systems would be a good drop in for speeding up the report ingestion.

## Other Ideas

Comment below, but implementation is more valuable than ideas at this time. :)

**Comment by smcgregor** [comment]
I labeled this as "low effort" not because I think this should be closed with less than a day's effort, but because I think meaningful incremental progress is possible on this without solving the problem in its full scope.

**Comment by smcgregor** [comment]
Other longer implementation time ideas include running everything in a document embedding or generating pairwise semantic similarity scores. Initially I think we should start with publication date checks and MongoDB's inbuilt functions for similarity.

**Comment by jt-mchorse** [comment]
Tagging system can benefit us in long run. At incident submission, if we tag top 5 appearing words and ask reporters to put at least 3 category tags mandatory, we can manage submitted reports in organised way. At submission form, we should show similar incidents based on shared number of tags and it will make reporters put cases in existing incidents than submitting new.

TagInput should have an autocomplete function to let reporters easily pick up existing tags.
Adding tag filtering feature to submitted page will help us grouping incidents.

**Comment by smcgregor** [comment]
Taxonomies (i.e., tags) are meant to be formally defined and applied, but we can potentially scope one namespace as closer to a wiki. These tags could then be used primarily for deduplication purposes.

The word frequency tagging is likely to be pretty rough and I would not start there.

I think returning incidents based on dates is likely to be the most impact at the least amount of effort.

**Comment by jt-mchorse** [comment]
I agree with using report date as a starting point, those taxonomies can be used the later stages after passing enough tests.

**Comment by smcgregor** [comment]
@alexmcode next step on this one is to show related incident reports in the review queue according to the publication date or incident ID.
