### ISSUE TITLE
SSR of Word Counts Produces Bloat

### ISSUE THREAD

**Issue by smcgregor** [PartnershipOnAI/aiid#56]
The [wordcounts](https://incidentdatabase.ai/summaries/wordcounts) page currently has long load times, likely because the server side rendering of the page produces a giant blob that should be made more efficient. The load time of the page after SSR should be nearly immediate.

**Comment by jt-mchorse** [comment]
Gatsby doesn't really do SSR, instead it uses static HTML files generated on build. I profiled the page rendering and it usually takes around 1 second to get the component rendered, most time spent on counting words. around 900ms each time, I've been doing some research and we can reduce it by using template and doing word count on gatsby-node.js, so we precalculate the words and just do rendering of counted words and cloud on page.

**Comment by smcgregor** [comment]
Interesting, so we need collections of scripts that generate data like word counts that are then consumable by the components?
