### ISSUE TITLE
Improve look and feel of citation page

### ISSUE THREAD

**Issue by smcgregor** [PartnershipOnAI/aiid#69]
The citation pages (e.g., [example](https://incidentdatabase.ai/cite/1)) is currently pretty rough. The headers don't have enough padding, additional data for the reports could be presented in an artful manner, and in general the visual design could be improved. I think a series of small merge requests are warranted for:

1. Improving the typography/layout of the current content.
2. Adding additional fields and data to the list of reports.
3. Adding more functionality to the page (e.g., timelines, links to similar incidents, etc.)

**Comment by jt-mchorse** [comment]
Instead of `react-bootstrap`'s button, we should always use Gatsby [Link](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link) to preload the pages.

**Comment by smcgregor** [comment]
This has since improved.
