### ISSUE TITLE
Title on "Leaderboard" is "Incident List"

### ISSUE THREAD

**Issue by smcgregor** [PartnershipOnAI/aiid#79]
Visit: https://incidentdatabase.ai/summaries/leaderboard. 
Current title: "Incident List". 
Expected: Something like "Submissions Leaderboard"

**Comment by alexmcode** [comment]
Hi, @smcgregor I see that we also have title `incident List` for page `summaries/wordcounts`. Is this how it should be or should we fix this (if yes, in this issue or a different one)?

**Comment by smcgregor** [comment]
Thanks @alexmcode, please knock out both at once. This is my overzealous copy/pasting.
