### ISSUE TITLE
Update templates to have some pages without the sidebars

### ISSUE THREAD

**Issue by smcgregor** [PartnershipOnAI/aiid#82]
The [discover](https://incidentdatabase.ai/discover/index.html?s=) application is presently in its own static JS application rather than inside the Gatsby SSR pipeline. The first step to unifying these two applications is to have a template that removes the sidebars from the app. Then database apps can optionally have their own scripting environment (as is true with the current discover app), or be included in the Gatsby SSR build. After this issue is resolved, we should develop a simplistic visualization (e.g., a timeline visualization) as a test case. If the look and feel is good, then we can begin unifying the apps.

**Comment by alexmcode** [comment]
@smcgregor a clarification question for myself: should we remove the sidebar altogether or find a way to hide it/make it collapsible? I'm assuming the second option since we want the user to access the rest of the app.

**Comment by smcgregor** [comment]
Likely collapsible and automatically collapsing when it goes to some pages.

**Comment by alexmcode** [comment]
@smcgregor this can be close?

**Comment by smcgregor** [comment]
Yep!
