### ISSUE TITLE
Update 404 Page

### ISSUE THREAD

**Issue by smcgregor** [PartnershipOnAI/aiid#86]
The current 404 page for the site looks like the following,

<img width="741" alt="Screen Shot 2021-02-06 at 9 22 46 AM" src="https://user-images.githubusercontent.com/64780/107125176-2364fc00-685d-11eb-8edd-97db14114a14.png">

This is the default 404 page for Netlify. An updated page should contain links back to the root page of the site and graphic.

**Comment by rijusougata13** [comment]
is not back to our site link does the same job?

**Comment by smcgregor** [comment]
Yes, but the screen shot above has completely different styling from the site and the messaging targets developers rather than end users. In short, it is not user friendly.
